version: '3.8'
services:
  envoy:
    container_name: envoy
    tty: true
    stdin_open: true
    environment:
     - ENVOY_HOST=${HOST_EXTERNO}
     - ENVOY_PORT=$PORT
    volumes:
      - ../envoy/envoy.yaml:/tmpl/envoy.yaml
    networks:
      application:
          ipv4_address: ${HOST_EXTERNO}
    depends_on:
      - front
      - backend