version: '3.8'
services:
  db:
    restart: always
    container_name: db
    volumes:
      - ../database/prod:/var/lib/postgresql/data
    environment: 
      TZ: ${TIMEZONE}
      PGTZ: ${TIMEZONE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - application